org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.76
neo_version_range=[26.1.2.76,)
loader_version_range=[11,)

## Mod Properties
mod_id=havendaydisplay
mod_name=HavenDayDisplay
mod_license=All Rights Reserved
mod_version=1.0.2
mod_group_id=net.cathienova.havendaydisplay
mod_authors=CathieNova
mod_description=A mod that displays the current minecraft day as an overlay on the screen.