modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
    modId="havendaydisplay"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"
    description='''${mod_description}'''
[[dependencies.havendaydisplay]]
    modId="neoforge"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="CLIENT"
[[dependencies.havendaydisplay]]
    modId="minecraft"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"